<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Capisuite-users] Error when sending a fax
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/capisuite-users/2010-January/index.html" >
   <LINK REL="made" HREF="mailto:capisuite-users%40lists.berlios.de?Subject=Re%3A%20%5BCapisuite-users%5D%20Error%20when%20sending%20a%20fax&In-Reply-To=%3C4B5F3368.8040701%40forestfactory.de%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   
   <LINK REL="Next"  HREF="000008.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Capisuite-users] Error when sending a fax</H1>
    <B>Magnus Rosenbaum</B> 
    <A HREF="mailto:capisuite-users%40lists.berlios.de?Subject=Re%3A%20%5BCapisuite-users%5D%20Error%20when%20sending%20a%20fax&In-Reply-To=%3C4B5F3368.8040701%40forestfactory.de%3E"
       TITLE="[Capisuite-users] Error when sending a fax">cmr_lists at forestfactory.de
       </A><BR>
    <I>Tue Jan 26 19:24:40 CET 2010</I>
    <P><UL>
        
        <LI>Next message: <A HREF="000008.html">[Capisuite-users] Error when sending a fax
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#7">[ date ]</a>
              <a href="thread.html#7">[ thread ]</a>
              <a href="subject.html#7">[ subject ]</a>
              <a href="author.html#7">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hello everybody!

I've been using Capisuite for sending and receiving faxes for years, but
now it suddenly refuses to send faxes anymore. Instead I get:

<A HREF="https://lists.berlios.de/mailman/listinfo/capisuite-users">magnum at ipx20010</A>:~&gt; capisuitefax -d 08970066686 Vertragsuebernahme.pdf
Traceback (most recent call last):
  File &quot;/usr/bin/capisuitefax&quot;, line 194, in ?
    newname=cs_helpers.uniqueName(sendq,&quot;fax&quot;,&quot;sff&quot;)
  File &quot;/usr/lib/python2.4/site-packages/cs_helpers.py&quot;, line 128, in
uniqueName
    nextnr=int(countfile.readline())
ValueError: invalid literal for int():

I did not change anything on this machine! I also compared the files with
the backup from when it definitly worked last time, but found no
difference. I also rebooted the machine, the harddisc is not full and
everything else also looks fine.

Any ideas?

cu, Magnus

-- 
Carl Magnus Rosenbaum M.A.
Administration - Programmierung - Weiterbildung     <A HREF="http://cmr.cx/">http://cmr.cx/</A>
Tel: +49 89 70066626  Fax: +49 89 70066686  Mobil: +49 163 1737001
PGP Fingerprint: DEBC 3C99 EF1D 74F0 D4C7 EFF5 C268 3690 0EA1 7641

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	
	<LI>Next message: <A HREF="000008.html">[Capisuite-users] Error when sending a fax
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#7">[ date ]</a>
              <a href="thread.html#7">[ thread ]</a>
              <a href="subject.html#7">[ subject ]</a>
              <a href="author.html#7">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/capisuite-users">More information about the Capisuite-users
mailing list</a><br>
</body></html>
